---
meta:
  jobs:
    consul:
      persistent_disk_pool: small
    etcd:
      persistent_disk_pool: large
    blobstore:
      persistent_disk_pool: xlarge
    postgres:
      persistent_disk_pool: medium
    database:
      persistent_disk_pool: small

jobs:
- name: consul_z1
  instances: 1
  .: (( inject meta.jobs.consul ))
  resource_pool: warden
  networks:
  - name: cf
    static_ips: (( static_ips(52, 53, 54)  ))
  properties:
    metron_agent:
      zone: z1
- name: ha_proxy_z1
  instances: 1
  .: (( inject meta.jobs.ha_proxy ))
  resource_pool: warden
  networks:
  - name: cf
    static_ips: (( static_ips(32) ))
  properties:
    metron_agent:
      zone: z1
    ha_proxy:
      ssl_pem: | # *.bosh-lite.com cert from cf-release, override if using non-traditional bosh-lite
          -----BEGIN CERTIFICATE-----
          MIICsjCCAZoCCQC+xvE/1ZQgFzANBgkqhkiG9w0BAQUFADAaMRgwFgYDVQQDFA8q
          LmJvc2gtbGl0ZS5jb20wIBcNMTUxMDA4MjIwNDQ3WhgPMjI4OTA3MjIyMjA0NDda
          MBoxGDAWBgNVBAMUDyouYm9zaC1saXRlLmNvbTCCASIwDQYJKoZIhvcNAQEBBQAD
          ggEPADCCAQoCggEBAK09Q520xrKx75uew3mAS+y4uyRPZPEjt/pYdBl40PXIwaqO
          X7LGoc9lNZS/eAPX6xeVFmZbLZReQ5+Fm0moeLzsh58W9jjkWWk7oGISmxfoQz9B
          X9Eh0NHCrtKXMrCPlr+2RI/qLinJDqn87UEZqwX+84JU8hBZ8RD8D7YnfuDteySV
          SYOEUjkiN/pIWmbJQY1sjEyk1zH1Hiy8kmnait2sX8Td2S/aV6EJBgODOstzEtnf
          HFDIfoTJxbSK/0TbF6qBaSl0CLaOop9FX2ULEZUgAuIW4dG2k/xnpMLdz7A0ZsSU
          Haw9okZ5wNuYk1RSqhnqw+9KUWgXwV6RlMvtXMkCAwEAATANBgkqhkiG9w0BAQUF
          AAOCAQEAShOqAFLIc93yIjhcnN7L4ZXFo+CvOgklJqFeBbwRshsEptbaddDJYmRr
          ZXzOE7MiTOBM8YzKqtHvl/ZguXmIAXSZlnq6kuJHdPtcZOqu1x2GAvWWOzn9Xl4m
          T3RmwF3NgiX0jgNMkkm8i8jfT7uN9BnHxMv65b9yKeM0sRFN5XigA43DDQnfF3j4
          FQ9jwpmS7zOx2wn6FayOgoE4rgJfV/9637ZprQOMfUbZPKgQQplDn6bvK13rj9g9
          zCC9W0fy29l7VDuAOOSI5xzsoYyH6DfX7oySxn291hidSCb/buadNG4dgI4keMGw
          u5K8QQYmlSY91IJtuRRITYXGmIiPpg==
          -----END CERTIFICATE-----
          -----BEGIN RSA PRIVATE KEY-----
          MIIEogIBAAKCAQEArT1DnbTGsrHvm57DeYBL7Li7JE9k8SO3+lh0GXjQ9cjBqo5f
          ssahz2U1lL94A9frF5UWZlstlF5Dn4WbSah4vOyHnxb2OORZaTugYhKbF+hDP0Ff
          0SHQ0cKu0pcysI+Wv7ZEj+ouKckOqfztQRmrBf7zglTyEFnxEPwPtid+4O17JJVJ
          g4RSOSI3+khaZslBjWyMTKTXMfUeLLySadqK3axfxN3ZL9pXoQkGA4M6y3MS2d8c
          UMh+hMnFtIr/RNsXqoFpKXQIto6in0VfZQsRlSAC4hbh0baT/Gekwt3PsDRmxJQd
          rD2iRnnA25iTVFKqGerD70pRaBfBXpGUy+1cyQIDAQABAoIBACXzdt2UnbbF3jzU
          QfRbE8bvDSg+MFnXPlWcjQqLehNuAGcxu2s5snbxsBQ/Abat1XWcFoUj0k9feyb2
          KPew7YpNssQ6ToRWGfRAuLjjZJCPNDQmSSxSYSGiqZO+xb8CJb8n2ctBPQ2wWwMI
          Qp1xVxMAMC5MF59XZMUYwwRfkJ8LawB90+S9BjHcU3GqoPECLFkgEeIj3mrnmpAD
          vhIeYvQj2W5JCpxLUA+7lnyoqnx8OTOXvBPAsKwO1Hx88yCitnxXro7i0ZAw4ErH
          zrnMgWkFDvRiS3ta/QS2RcBBiZHKX/gRRT/AvqJ+Erveu0BcZ9AVy1UpPB0w9rBK
          PTxS2BECgYEA3MLd6Og+xQpw4UNhy9EjeDE/b/rZK4w/vfD3WE5J3Nm4HGdSA6Q4
          YmQYVg+VuCLR+HHsk58LxEf+cU0MNgDJR1/rFZRmociF+G0i7/7DuhFm891wWWGW
          Iz7XeGWHi+LIeYWkteuflrkmvy/7xqArgcNqnirGhba6706MZz0G0YUCgYEAyOR5
          aF7qRpLXHgMOPOzJKC4ceWA5rY8rcdJZFI7aNq5MJF9o+fNNt8YRJ1hQTzs5K/R+
          HwBJel8J6CoPQo9WUXnj0md4M67sCZSBqWANMO/J0f4VkbLS/lwch+ZPS8jt3Z4z
          umYW4QnloIKXxORfySo7r9DzZSgmxuDE8PVWn3UCgYAFTwpXF36q7l1YjW5EoHrh
          4Q1NfBLM4UqHHsxT604LaZDr3fAy9jgE5bNQHn/TNcMm3lZ6FlEKH1EXGGs6wToV
          5VCZ7D+rlE7kcntsmgvK5bA8HQ8elyItJs23r3la+9EmWvhjB4+G6FzuLBE57ZAe
          RrzBoPW1MXe9WX423VjUoQKBgGea5T49jSc+fbDdtI8ZMxkExuyWAskOyEIYUJa4
          obOHqn8rsZEOuKspfBlFg42JJpATtKO6WyrALvTMFDiogcTdTvBpKmXFNbgvHbvD
          bKorUHN7TZZpmkVSLeisj4KvKnWcLGNaWTxQBVwFXc5OVVQC8utWoOAvl+gDba4z
          aSwtAoGANdquHRNbigPj2y0cRoexYJwKgpfGEK4HXitsKZUUg09gVfagM1HynVFz
          RA0LVac0oJZFdMYZyU/PXCySS237xUD2/0oySYJIK9E0C4ZxKD+DoAk5Z097z0LM
          7rxStMCBWB2x4ommvEnpdgntEKkl4buIDatvmbdmdwkY3+X65Ks=
          -----END RSA PRIVATE KEY-----
- name: nats_z1
  instances: 1
  .: (( inject meta.jobs.nats ))
  properties:
    metron_agent:
      zone: z1
  resource_pool: warden
  networks:
  - name: cf
    static_ips: (( static_ips(4) ))
- name: etcd_z1
  instances: 1
  .: (( inject meta.jobs.etcd ))
  properties:
    metron_agent:
      zone: z1
  resource_pool: warden
  networks:
  - name: cf
    static_ips: (( static_ips(40, 41) ))
- name: blobstore_z1
  instances: 1
  .: (( inject meta.jobs.blobstore ))
  properties:
    metron_agent:
      zone: z1
  resource_pool: warden
  networks:
  - name: cf
- name: postgres_z1
  instances: 1
  .: (( inject meta.jobs.postgres ))
  properties:
    metron_agent:
      zone: z1
  resource_pool: warden
  networks:
  - name: cf
    static_ips: (( static_ips(28) ))
- name: uaa_z1
  instances: 1
  .: (( inject meta.jobs.uaa ))
  properties:
    metron_agent:
      zone: z1
  resource_pool: warden
  networks:
  - name: cf
- name: api_z1
  instances: 1
  .: (( inject meta.jobs.api ))
  properties:
    metron_agent:
      zone: z1
  resource_pool: warden
  networks:
  - name: cf
- name: clock_global
  instances: 1
  .: (( inject meta.jobs.clock ))
  properties:
    metron_agent:
      zone: z1
  resource_pool: warden
  networks:
  - name: cf
- name: api_worker_z1
  instances: 1
  .: (( inject meta.jobs.api_worker ))
  properties:
    metron_agent:
      zone: z1
  resource_pool: warden
  networks:
  - name: cf
- name: doppler_z1
  instances: 1
  .: (( inject meta.jobs.doppler ))
  properties:
    doppler:
      zone: z1
    metron_agent:
      zone: z1
  resource_pool: warden
  networks:
  - name: cf
- name: loggregator_trafficcontroller_z1
  instances: 1
  .: (( inject meta.jobs.trafficcontroller ))
  properties:
    metron_agent:
      zone: z1
  resource_pool: warden
  networks:
  - name: cf
- name: router_z1
  instances: 1
  .: (( inject meta.jobs.router ))
  properties:
    metron_agent:
      zone: z1
  resource_pool: warden
  networks:
  - name: cf
    static_ips: (( static_ips(20) ))
- name: database_z1
  instances: 1
  .: (( inject meta.jobs.database ))
  properties:
    metron_agent:
      zone: z1
  resource_pool: warden
  networks:
  - name: cf
- name: brain_z1
  instances: 1
  .: (( inject meta.jobs.brain ))
  properties:
    metron_agent:
      zone: z1
  resource_pool: warden
  networks:
  - name: cf
- name: cell_z1
  instances: 1
  .: (( inject meta.jobs.cell ))
  properties:
    diego:
      rep:
        use_azure_fault_domains: null
        zone: z1
    metron_agent:
      zone: z1
  resource_pool: warden
  networks:
  - name: cf
- name: cc_bridge_z1
  instances: 1
  .: (( inject meta.jobs.cc_bridge ))
  properties:
    metron_agent:
      zone: z1
  resource_pool: warden
  networks:
  - name: cf
- name: route_emitter_z1
  instances: 1
  .: (( inject meta.jobs.route_emitter ))
  properties:
    metron_agent:
      zone: z1
  resource_pool: warden
  networks:
  - name: cf
- name: access_z1
  instances: 1
  .: (( inject meta.jobs.access ))
  properties:
    metron_agent:
      zone: z1
  resource_pool: warden
  networks:
  - name: cf
- name: acceptance_tests
  networks:
  - name: cf
  resource_pool: warden
- name: smoke_tests
  networks:
  - name: cf
  resource_pool: warden
