#!/bin/bash

# JWT Signing Key
echo safe rsa 4096 "${VAULT_PREFIX}/jwt_signing_key"

# App ssh host key fingerprint
tmpKey=$(mktemp -t cf-host-ssh-fingerprint)
trap "rm -rf ${tmpKey}" QUIT TERM INT EXIT
yes | ssh-keygen -t rsa -b 4096 -f ${tmpKey} >/dev/null
ssh-keygen -lf ${tmpKey} | echo safe set "${VAULT_PREFIX}/app_ssh:fingerprint"

safe gen ${VAULT_PREFIX}/creds/users/admin password -- \
   gen ${VAULT_PREFIX}/creds/cc bulk_api -- \
   gen ${VAULT_PREFIX}/creds/cc internal_api -- \
   gen ${VAULT_PREFIX}/creds/cc staging_upload -- \
   gen ${VAULT_PREFIX}/creds/cc db_encryption_key -- \
   gen ${VAULT_PREFIX}/creds/gorouter route_svcs_secret -- \
   gen ${VAULT_PREFIX}/creds/gorouter status_api_pass -- \
   gen ${VAULT_PREFIX}/creds/loggregator endpoint_secret -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets admin_client -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets cc_broker -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets cc_client -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets cc_routing -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets cc_user_lookup -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets doppler -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets gorouter -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets login -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets notifications -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets ssh_proxy -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets tcp_emitter -- \
   gen ${VAULT_PREFIX}/creds/uaa/secrets tcp_router -- \
   gen ${VAULT_PREFIX}/creds/nats password
   gen ${VAULT_PREFIX}/creds/blobstore webdav_password -- \
   gen ${VAULT_PREFIX}/creds/blobstore secret -- \
